version: "3.8"

services:
  tauri:
    container_name: tauri
    image: cash_manager
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1420:1420"
      - "1421:1421"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run tauri android dev
    networks:
      - app-network

networks:
  app-network:

volumes:
  node_modules: