name: build-sign-mobile

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-sign-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.keystore

      - name: Build Docker Image
        run: docker build -f ./docker/production/Dockerfile -t myapp-builder .

      - name: Create Container and Extract AAB
        run: |
          docker create --name temp-container myapp-builder
          docker cp temp-container:/src-tauri/gen/android/app/build/outputs/bundle/release/app-release.aab ./app-release.aab
          docker rm temp-container

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: ./app-release.aab
          retention-days: 1