name: build_deploy_cluster_production

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_deploy_cluster_production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t your-app .

      - name: Run Docker Container
        run: docker run --name myappcontainer your-app

      - name: Copy APK and AAB from Container
        run: |
          docker cp myappcontainer:/path/in/container/app-release.apk .
          docker cp myappcontainer:/path/in/container/app-release.aab .

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: app-release.aab