name: build-sign-mobile

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-sign-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java JDK LTS
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.8'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x src-tauri/gen/android/gradlew

      - name: Build and Sign AAB
        run: ./gradlew bundleRelease
        working-directory: src-tauri/gen/android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: src-tauri/gen/android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 1